editor/blog/urls.py
from django.urls import path

from editor.blog import views


app_name = 'blog'
urlpatterns = [
    path('', views.home_view, name="home"),
    path('contact/', views.contact_view, name="contact"),
    path('about/', views.about_view, name="about"),
    # path('post/', views.post_view, name="post"),
    path(
        'posts/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"
    ),
    path(
        'posts/latest/', views.PostLatestView.as_view(), name="post_latest"
    ),
    path('404/', views.page_not_found_view, name="404"),
    path('page/', views.BlogListView.as_view(), name="blog_page"),
]

editor/urls.py
from django.contrib import admin
from django.urls import path, include
from editor.editor import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('def_admin/', admin.site.urls),
    path('', include('editor.blog.urls')),
    path('admin/', include('editor.blog_admin.urls')),
    path('upload/', views.upload_view, name="upload"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

editor/blog/models.py
from django.db import models

editor/blog_admin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.http import Http404
# from django.contrib.auth.validators import UnicodeUsernameValidator
# from django.utils.translation import gettext_lazy as _
# from validator import Validator


class Hashtags(models.Model):
    text = models.CharField(max_length=35, unique=True)


POST_STATUSES = [
    ('DR', 'Draft'),
    ('ST', 'Stash'),
    ('PB', 'Public'),
]


# class UsernameValidatorAllowSpaces(UnicodeUsernameValidator):
#     regex = r'^[\w\' _-]+\Z'
#     message = _(
#         'Enter a valid username. This value may contain only letters, '
#         'numbers, spaces and -/_/\' characters.'
#     )


# class UsernameValidatorAllowSpaces(Validator):
#     username = 'required|regex:^[\w\' _-]+\Z'

#     message = {
#         'username': {
#             'required': _('username is required'),
#             'regex': _(
#                 'Enter a valid username. This value may contain only letters, '
#                 'numbers, spaces and -/_/\' characters.'
#             )
#         }
#     }


# class UserModel(User):
#     username_validator = UsernameValidatorAllowSpaces

#     class Meta:
#         proxy = True


class Post(models.Model):
    # ToDo: Reduce length to 50 chars
    title = models.CharField(max_length=80)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts'
    )
    description = models.CharField(max_length=300)
    hashtags = models.ManyToManyField(Hashtags)
    content = models.TextField()
    post_date = models.DateField(auto_now_add=True)
    modified_date = models.DateField(auto_now=True)
    # ToDo: add image load via the file input
    # or via the url input (if image is hosted somewhere else)
    preview_img_url = models.CharField(max_length=300)
    post_status = models.CharField(
        max_length=2, choices=POST_STATUSES, default='DR'
    )
    
    class Meta:
        ordering = ['post_date']

    def __str__(self):
        return (
            f'{self.post_date.strftime("%d.%m.%Y %H:%M")} - \"{self.title}\"'
        )

    def get_first_tag(self):
        """Return first hashtag from prepopulated list.

        Warning: prefetch_related call required before running this function.
        Works only on prepopulated tags list.
        """
        try:
            return self.tags[0].text
        except AttributeError:
            # ToDo: add logging
            return ''
        except IndexError:
            # ToDo: add logging
            return ''

    def get_published_posts_by_date():
        """Select published posts and order them by modified date.

        Also Prepopulates related hashtags and saves them
        to the tags field.
        """
        # ToDo: switch post_status to published
        queryset = Post.objects.filter(post_status='DR')
        
        tag_prefetch = models.Prefetch('hashtags', to_attr='tags')
        queryset = Post.objects.prefetch_related(tag_prefetch)

        queryset = queryset.order_by('-modified_date')
        return queryset.defer('content')

editor/blog/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import HttpResponse
from django.conf import settings

from editor.blog_admin.models import Post as PostModel


def home_view(request):
    return render(request, 'home-masonry.html')


def page_not_found_view(request):
    return render(request, 'page-404.html')


def contact_view(request):
    return render(request, 'page-contact.html')


def about_view(request):
    return render(request, 'page-about.html')


class BlogListView(ListView):
    def __init__(self):
        self.paginate_by = settings.POSTS_PER_PAGE
        self.context_object_name = 'post_list'
        self.queryset = PostModel.get_published_posts_by_date()
        self.template_name = 'post_tiles.html'
        self.allow_empty = False


class PostDetailView(DetailView):
    model = PostModel
    template_name = 'post-detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Retrieving linked tags from the db
        tags = self.object.hashtags.values()
        # Parsing tag objects and getting text values
        context['hashtags'] = [tag['text'] for tag in tags]

        return context


class PostLatestView(PostDetailView):

    def get_object(self, queryset=None):
        post = PostModel.objects.latest('modified_date')
        return post

editor/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <title>{% block title %}Ada Blog{% endblock title%}</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">

    <!-- Vendor Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha256-aAr2Zpq8MZ+YA/D6JtRD3xtrwpEz2IqOS+pWD/7XKIw=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" integrity="sha256-PHcOkPmOshsMBC+vtJdVr5Mwb7r0LkSVJPlPrp/IMpU=" crossorigin="anonymous" />

    <!-- Theme Styles -->
    <link href="{% static 'css/ada.css' %}" rel="stylesheet">
    <link href="{% static 'css/ada-themes.css' %}" rel="stylesheet">

    <!-- Extra Styles -->
    {% block extracss %}{% endblock extracss %}
    
    <!-- Vendor Scripts -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.2/umd/popper.min.js" integrity="sha256-XahKYIZhnEztrOcCTmaEErjYDLoLqBoDJbVMYybyjH8=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha256-OFRAJNoaD8L3Br5lglV7VyLRf0itmoBzWUoM+Sji4/8=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha256-z6FznuNG1jo9PP3/jBjL6P3tvLMtSwiVAowZPOgo56U=" crossorigin="anonymous"></script>

    <!-- Theme Scripts -->
    <script defer src="{% static 'js/blog.js' %}"></script>

    <!-- Extra Scripts -->
    {% block extrajs %}{% endblock extrajs %}

    <!-- HTML5 shiv for IE8 support -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="loading"></div>

    <div id="header">
      <div class="top">
        <div class="search">
          <form role="form">
            <div class="form-group has-feedback">
              <input type="text" class="form-control input-sm" placeholder="Search.." />
              <i class="form-control-feedback fa fa-search"></i>
            </div>
          </form>
        </div>
        <a class="brand" href="{% url 'blog:home' %}">
          <span>VDV</span>
        </a>
      </div>

      <nav class="navbar navbar-expand-lg navbar-light navbar-ada">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:home'%}" id="dropdown1">Home</a>
            </li>

            <li class="dropdown">
              <a class="nav-link" href="{% url 'blog:post_latest' %}" id="dropdown2">Posts</a>
            </li>

            <li class="dropdown">
              <a class="nav-link" href="{% url 'blog:about' %}" id="dropdown3">About</a>
            </li>

            <li class="dropdown">
              <a class="nav-link" href="{% url 'blog:contact' %}" id="dropdown4">Contact</a>
            </li>

            <li class="dropdown">
              <a class="nav-link" href="{% url 'blog:404' %}" id="dropdown5">404</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    {% block content %}{% endblock content %}

    <div id="footer">
      <div id="subscribe">
        <div class="container">

          <div class="form-inline justify-content-center">
            <div class="form-group">
              <p>Stay updated on latest updates &amp; promotions</p>
            </div>
            <div class="form-group">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Your email address">
                <span class="input-group-btn">
                  <button class="btn ada-btn btn-ada-dark" type="button">Subscribe</button>
                </span>
              </div>
            </div>
          </div>

        </div>
      </div>
      <div id="links">
        <div class="container">
          <div class="row">
            <div class="col-sm-2">
              <p class="brand">
                <a href="{% url 'blog:home' %}">
                  <span>VDV</span>
                </a>
              </p>
            </div>
            <div class="col-sm-8">
              <ul class="list-inline">
                <li class="list-inline-item"><a href="{% url 'blog:home' %}">Home</a></li>
                <li class="list-inline-item"><a href="{% url 'blog:about' %}">About</a></li>
                <li class="list-inline-item"><a href="{% url 'blog:contact' %}">Contact</a></li>
              </ul>
            </div>
            <div class="col-md-2">
              <ul class="list-inline">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <a id="scroll-to-top">
      <i class="fa fa-angle-up"></i>
    </a>

  </body>
</html>

editor/blog/templates/home-masonry.html
{% extends 'base.html' %}
{% load static %}
{% load media %}

{% block title %}Blog home{% endblock title %}

    {% block content %}
    <div id="posts" class="container">
      <div class="row">
        <section class="col-md-8 wow fadeIn">
          <div class="post">
            <div class="row">
              <div class="col-md-6 media">
                <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity31.jpg' %}" class="img-fluid" />
              </div>
              <div class="col-md-6 caption">
                <span class="post-tag">#music</span>
                <a href="{% url 'blog:post_latest' %}" class="post-title">Don't look at me</a>
                <span class="post-date">19 Sept 2015</span>
                <p class="post-description">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis <a href="#">parturient montes</a>, nascetur ridiculus mus. Aenean commodo ligula eget dolor.</p>
              </div>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn">
          <div class="post">
            <div class="media">
              <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity4.jpg' %}" class="img-fluid" />
            </div>
            <div class="caption text-center">
              <a href="{% url 'blog:post_latest' %}" class="post-title">I'm only breathing</a>
              <span class="post-date">6 Sept 2015</span>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn">
          <div class="quote">

            <i class="quote-left fa fa-quote-left"></i>
            <i class="quote-right fa fa-quote-right"></i>

            <div class="text-center">
              <img src="{% static 'img/matt-berninger.jpg' %}" class="quote-face" />
              <blockquote>
                <p>Don't look at me I'm indiscreet</p>
                <footer>Matt Berninger</footer>
              </blockquote>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn">
          <div class="post">
            <div class="media">
              <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity6.jpg' %}" class="img-fluid" />
            </div>
            <div class="caption text-center">
              <a href="{% url 'blog:post_latest' %}" class="post-title">You're sharp alright</a>
              <span class="post-date">6 Aug 2015</span>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn">
          <div class="post">
            <div class="caption">

              <div class="post-thumb">
                <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity31.jpg' %}" class="img-fluid" />
              </div>

              <span class="post-tag">#music</span>
              <a href="{% url 'blog:post_latest' %}" class="post-title">Leave it alone</a>
              <p class="post-description">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
              <br />
              <br />
              Cum sociis natoque penatibus et magnis dis parturient montes magnis dis parturient montes, nascetur ridiculus mus. Aenean commodo <a href="#">ligula eget dolor</a>.</p>
              <span class="post-date">13 June 2015</span>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn" style="display:none;">
          <div class="post">
            <div class="media">
              <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity10.jpg' %}" class="img-fluid" />
            </div>
            <div class="caption text-center">
              <a href="{% url 'blog:post_latest' %}" class="post-title">Can we</a>
              <span class="post-date">12 Apr 2015</span>
            </div>
          </div>
        </section>

        <section class="col-md-8 wow fadeIn" style="display:none;">
          <div class="post">
            <div class="row">
              <div class="col-md-6 caption">
                <span class="post-tag">#music</span>
                <a href="{% url 'blog:post_latest' %}" class="post-title">Show a little discipline</a>
                <span class="post-date">23 Mar 2015</span>
                <p class="post-description">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. <a href="#">Aenean massa</a>. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean commodo ligula eget dolor.</p>
              </div>
              <div class="col-md-6 media">
                <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity31.jpg' %}" class="img-fluid" />
              </div>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn" style="display:none;">
          <div class="post">
            <div class="media">
              <img src="{% media 'uploads/DeathtosStockSerenity9.jpg' %}" class="img-fluid" />
            </div>
            <div class="caption text-center">
              <a href="{% url 'blog:post_latest' %}" class="post-title">Loose lips</a>
              <span class="post-date">3 Jan 2015</span>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn" style="display:none;">
          <div class="post">
            <div class="media">
              <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity2.jpg' %}" class="img-fluid" />
            </div>
            <div class="caption text-center">
              <a href="{% url 'blog:post_latest' %}" class="post-title">Sink</a>
              <span class="post-date">7 Sept 2014</span>
            </div>
          </div>
        </section>

        <section class="col-md-4 wow fadeIn" style="display:none;">
          <div class="post">
            <div class="media">
              <img src="{% media 'uploads/DeathtoStock_EnergyandSerenity5.jpg' %}" class="img-fluid" />
            </div>
            <div class="caption text-center">
              <a href="{% url 'blog:post_latest' %}" class="post-title">Ships</a>
              <span class="post-date">18 July 2014</span>
            </div>
          </div>
        </section>

        <div class="col-md-12">
          <div class="text-center">
            <a href="#" class="btn ada-btn btn-ada-light load-more">Older posts</a>
          </div>
        </div>

      </div>
    </div>
    {% endblock content %}

editor/blog/templates/page-404.html
{% extends 'base.html' %}
    {% block content%}
    <div id="single">
      <div class="container">
        <div class="page-404">

          <h1>404</h1>
          <h2>That's an error!</h2>
          <p>The requested URL was not found on this server.</p>
          <a class="btn ada-btn btn-ada-dark" href="{% url 'blog:home' %}">Back to Home</a>

        </div>
      </div>
    </div>
    {% endblock content %}

editor/blog/templates/page-about.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <div id="single">
      <div class="container">
        <div class="post">
          <div class="caption">
            <div class="header">
              <img src="{% static 'img/avatar.png' %}" class="avatar img-circle" />

              <h1>About me</h1>
            </div>

            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque <a href="#">penatibus</a> et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, <strong>pretium quis, sem.</strong></p>

            <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</p>

            <p><strong>Aliquam lorem ante</strong>, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. <strong>Etiam rhoncus</strong>. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante <a href="#">tincidunt tempus</a>.</p>

            <blockquote>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            </blockquote>

            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, <a href="#">nascetur ridiculus</a> mus. Donec quam felis, ultricies nec, pellentesque eu, <strong>pretium quis, sem.</strong></p>

            <div class="row">
              <div class="col-md-4">
                <ul>
                  <li>Donec quam felis</li>
                  <li>Consectetuer adipiscing</li>
                </ul>
              </div>
              <div class="col-md-4">
                <ul>
                  <li>Donec quam felis</li>
                  <li>Consectetuer adipiscing</li>
                </ul>
              </div>
              <div class="col-md-4">
                <ul>
                  <li>Donec quam felis</li>
                  <li>Consectetuer adipiscing</li>
                </ul>
              </div>
            </div>
            <p>Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. <strong>Etiam rhoncus</strong>. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante <a href="#">tincidunt tempus</a>.</p>
          </div>
        </div>
      </div>
    </div>
    {% endblock content %}

editor/blog/templates/page-contact.html
{% extends 'base.html' %}
    {% block content %}
    <div id="single">
      <div class="container">
        <div class="container">
          <iframe id="map" src="https://maps.google.com/maps?q=Softserve%20poland&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
        </div>
        <div class="post">
          <div class="caption">
            <div class="row contact-info">
              <div class="col-md-4 text-center">
                <i class="fa fa-home fa-4x"></i>
                <h4>Address</h4>
                <p>
                  59, Main Design Street<br />
                  Australia – Sydney 55433
                </p>
              </div>
              <div class="col-md-4 text-center">
                <i class="fa fa-phone fa-4x"></i>
                <h4>Phone</h4>
                <p>
                  Local: +1 (234) 567890<br />
                  Mobile: 1800 92 6543210
                </p>
              </div>
              <div class="col-md-4 text-center">
                <i class="fa fa-envelope-o fa-4x"></i>
                <h4>Email</h4>
                <p>
                  <a class="email" href="mailto:office@ada.io">office@ada.io</a><br />
                  <a class="email" href="mailto:hiring@ada.io">hiring@ada.io</a>
                </p>
              </div>
            </div>

            <div class="header">
              <h1>Drop us a line</h1>
            </div>

            <div class="row">
              <div class="col-md-6 m-md-auto">
                <form>
                  <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" placeholder="Name">
                  </div>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Email" required>
                  </div>
                  <div class="form-group">
                    <label for="company">Company</label>
                    <input type="text" class="form-control" id="company" placeholder="Company">
                  </div>
                  <div class="form-group">
                    <label for="message">Message</label>
                    <textarea placeholder="Message" class="form-control"></textarea>
                  </div>
                  <a type="submit" class="btn ada-btn btn-ada-dark">Send</a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock content %}

editor/blog/templates/post_tiles.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Post tiles{% endblock title %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'css/home_page_styles.css' %}" />
{% endblock extracss %}

{% block content %}
    <div id="posts" class="container">
        <div class="row">
            {% for post in post_list %}
                {% cycle 'tile-big.html' 'tile-bs-card.html' 'tile-bs-card.html' 'tile-big-reversed.html' as tile_name silent %}
                {% if forloop.counter0|divisibleby:2 %}
                    <div class="row">
                {% endif %}
                {% include tile_name %}
                {% if forloop.counter|divisibleby:2 or forloop.last %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

editor/blog/templates/tile-big-reversed.html
<section class="col-md-8 wow fadeIn">
    <div class="post">
        <div class="row">
            <div class="col-md-6 caption">
                <span class="post-tag">{{ post.get_first_tag }}</span>
                <a href="{% url 'blog:post_latest' %}" class="post-title">{{ post.title }}</a>
                <span class="post-date">{{ post.modified_date }}</span>
                <p class="post-description">{{ post.description }}</p>
            </div>
            <div class="col-md-6 media">
                <div class="thumbnail" style="background-image: url({{ post.preview_img_url }});"></div>
            </div>
        </div>
    </div>
</section>

editor/blog/templates/tile-big.html
<section class="col-md-8 wow fadeIn">
    <div class="post">
        <div class="row">
            <div class="col-md-6 media">
                <div class="thumbnail" style="background-image: url({{ post.preview_img_url }});"></div>
            </div>
            <div class="col-md-6 caption">
                <span class="post-tag">{{ post.get_first_tag }}</span>
                <a href="{% url 'blog:post_latest' %}" class="post-title">{{ post.title }}</a>
                <span class="post-date">{{ post.modified_date }}</span>
                <p class="post-description">{{ post.description }}</p>
            </div>
        </div>
    </div>
</section>